# Generated by Django 5.1.1 on 2024-10-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_catagory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_arrival',
            field=models.BooleanField(default=False, help_text='0-default,1-Trending'),
        ),
    ]
